# Pre-commit hooks for Heavy Optimizer Platform
# Install with: pre-commit install
# Run manually: pre-commit run --all-files

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: mixed-line-ending
        args: ['--fix=lf']

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.10
        args: ['--config=pyproject.toml']

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ['--settings-path=setup.cfg']

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ['--config=setup.cfg']
        additional_dependencies: [flake8-docstrings]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        args: ['--config-file=setup.cfg', '--ignore-missing-imports']
        additional_dependencies: [
          types-requests,
          types-PyYAML,
          pandas-stubs,
          numpy,
        ]
        files: ^backend/
        exclude: ^backend/tests/

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ['-r', 'backend/', '-ll', '-x', 'backend/tests/']
        files: ^backend/

  - repo: local
    hooks:
      - id: no-commit-to-main
        name: Don't commit to main branch
        entry: bash -c 'if [[ $(git branch --show-current) == "main" ]]; then echo "Direct commits to main branch are not allowed. Please create a feature branch."; exit 1; fi'
        language: system
        pass_filenames: false
        always_run: true