# Pre-commit hooks for Heavy Optimizer Platform
# Install: pip install pre-commit && pre-commit install

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-json
      - id: check-merge-conflict
      - id: check-ast
      - id: debug-statements
      - id: mixed-line-ending
        args: ['--fix=lf']

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.10
        args: ['--line-length=100']
        files: ^backend/

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ['--profile=black', '--line-length=100']
        files: ^backend/

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ['--max-line-length=100', '--extend-ignore=E203,W503']
        files: ^backend/
        additional_dependencies:
          - flake8-docstrings
          - flake8-bugbear
          - flake8-comprehensions

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        args: ['--ignore-missing-imports', '--show-error-codes']
        files: ^backend/
        additional_dependencies:
          - types-requests
          - types-PyYAML
          - pandas-stubs

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        args: ['-x', '--ff', '-m', 'smoke']
        stages: [commit]

      - id: no-heavydb-imports
        name: Check for HeavyDB imports in new Parquet code
        entry: 'from\s+(pymapd|heavyai|heavydb)'
        language: pygrep
        files: ^backend/lib/data_pipeline/.*\.py$
        exclude: ^backend/lib/heavydb_connector/

      - id: check-deprecation-notices
        name: Ensure deprecation notices for HeavyDB files
        entry: python scripts/check_deprecation_notices.py
        language: python
        files: '.*heavydb.*\.py$'
        pass_filenames: true

# CI-specific configuration
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: [pytest-check]  # Don't run tests in pre-commit CI